export const languageData = [
  { code: 'ab', name: 'Abkhaz', key: 'аҧсуа' },
  { code: 'aa', name: 'Afar', key: 'Afaraf' },
  { code: 'af', name: 'Afrikaans', key: 'Afrikaans' },
  { code: 'ak', name: 'Akan', key: 'Akan' },
  { code: 'sq', name: 'Albanian', key: 'Shqip' },
  { code: 'am', name: 'Amharic', key: 'አማርኛ' },
  { code: 'ar', name: 'Arabic', key: 'العربية' },
  { code: 'an', name: 'Aragonese', key: 'Aragonés' },
  { code: 'hy', name: 'Armenian', key: 'Հայերեն' },
  { code: 'as', name: 'Assamese', key: 'অসমীয়া' },
  { code: 'av', name: 'Avaric', key: 'авар мацӀ, магӀарул мацӀ' },
  { code: 'ae', name: 'Avestan', key: 'avesta' },
  { code: 'ay', name: 'Aymara', key: 'aymar aru' },
  { code: 'az', name: 'Azerbaijani', key: 'azərbaycan dili' },
  { code: 'bm', name: 'Bambara', key: 'bamanankan' },
  { code: 'ba', name: 'Bashkir', key: 'башҡорт теле' },
  { code: 'eu', name: 'Basque', key: 'euskara, euskera' },
  { code: 'be', name: 'Belarusian', key: 'Беларуская' },
  { code: 'bn', name: 'Bengali', key: 'বাংলা' },
  { code: 'bh', name: 'Bihari', key: 'भोजपुरी' },
  { code: 'bi', name: 'Bislama', key: 'Bislama' },
  { code: 'bs', name: 'Bosnian', key: 'bosanski jezik' },
  { code: 'br', name: 'Breton', key: 'brezhoneg' },
  { code: 'bg', name: 'Bulgarian', key: 'български език' },
  { code: 'my', name: 'Burmese', key: 'ဗမာစာ' },
  { code: 'ca', name: 'Catalan; Valencian', key: 'Català' },
  { code: 'ch', name: 'Chamorro', key: 'Chamoru' },
  { code: 'ce', name: 'Chechen', key: 'нохчийн мотт' },
  { code: 'ny', name: 'Chichewa; Chewa; Nyanja', key: 'chiCheŵa, chinyanja' },
  { code: 'zh', name: 'Chinese', key: '中文 (Zhōngwén), 汉语, 漢語' },
  { code: 'cv', name: 'Chuvash', key: 'чӑваш чӗлхи' },
  { code: 'kw', name: 'Cornish', key: 'Kernewek' },
  { code: 'co', name: 'Corsican', key: 'corsu, lingua corsa' },
  { code: 'cr', name: 'Cree', key: 'ᓀᐦᐃᔭᐍᐏᐣ' },
  { code: 'hr', name: 'Croatian', key: 'hrvatski' },
  { code: 'cs', name: 'Czech', key: 'česky, čeština' },
  { code: 'da', name: 'Danish', key: 'dansk' },
  { code: 'dv', name: 'Divehi; Dhivehi; Maldivian;', key: 'ދިވެހި' },
  { code: 'nl', name: 'Dutch', key: 'Nederlands, Vlaams' },
  { code: 'en', name: 'English', key: 'English' },
  { code: 'eo', name: 'Esperanto', key: 'Esperanto' },
  { code: 'et', name: 'Estonian', key: 'eesti, eesti keel' },
  { code: 'ee', name: 'Ewe', key: 'Eʋegbe' },
  { code: 'fo', name: 'Faroese', key: 'føroyskt' },
  { code: 'fj', name: 'Fijian', key: 'vosa Vakaviti' },
  { code: 'fi', name: 'Finnish', key: 'suomi, suomen kieli' },
  { code: 'fr', name: 'French', key: 'français, langue française' },
  { code: 'ff', name: 'Fula; Fulah; Pulaar; Pular', key: 'Fulfulde, Pulaar, Pular' },
  { code: 'gl', name: 'Galician', key: 'Galego' },
  { code: 'ka', name: 'Georgian', key: 'ქართული' },
  { code: 'de', name: 'German', key: 'Deutsch' },
  { code: 'el', name: 'Greek, Modern', key: 'Ελληνικά' },
  { code: 'gn', name: 'Guaraní', key: 'Avañeẽ' },
  { code: 'gu', name: 'Gujarati', key: 'ગુજરાતી' },
  { code: 'ht', name: 'Haitian; Haitian Creole', key: 'Kreyòl ayisyen' },
  { code: 'ha', name: 'Hausa', key: 'Hausa, هَوُسَ' },
  { code: 'he', name: 'Hebrew (modern)', key: 'עברית' },
  { code: 'hz', name: 'Herero', key: 'Otjiherero' },
  { code: 'hi', name: 'Hindi', key: 'हिन्दी, हिंदी' },
  { code: 'ho', name: 'Hiri Motu', key: 'Hiri Motu' },
  { code: 'hu', name: 'Hungarian', key: 'Magyar' },
  { code: 'ia', name: 'Interlingua', key: 'Interlingua' },
  { code: 'id', name: 'Indonesian', key: 'Bahasa Indonesia' },
  {
    code: 'ie',
    name: 'Interlingue',
    key: 'Originally called Occidental; then Interlingue after WWII',
  },
  { code: 'ga', name: 'Irish', key: 'Gaeilge' },
  { code: 'ig', name: 'Igbo', key: 'Asụsụ Igbo' },
  { code: 'ik', name: 'Inupiaq', key: 'Iñupiaq, Iñupiatun' },
  { code: 'io', name: 'Ido', key: 'Ido' },
  { code: 'is', name: 'Icelandic', key: 'Íslenska' },
  { code: 'it', name: 'Italian', key: 'Italiano' },
  { code: 'iu', name: 'Inuktitut', key: 'ᐃᓄᒃᑎᑐᑦ' },
  { code: 'ja', name: 'Japanese', key: '日本語 (にほんご／にっぽんご)' },
  { code: 'jv', name: 'Javanese', key: 'basa Jawa' },
  { code: 'kl', name: 'Kalaallisut, Greenlandic', key: 'kalaallisut, kalaallit oqaasii' },
  { code: 'kn', name: 'Kannada', key: 'ಕನ್ನಡ' },
  { code: 'kr', name: 'Kanuri', key: 'Kanuri' },
  { code: 'ks', name: 'Kashmiri', key: 'कश्मीरी, كشميري‎' },
  { code: 'kk', name: 'Kazakh', key: 'Қазақ тілі' },
  { code: 'km', name: 'Khmer', key: 'ភាសាខ្មែរ' },
  { code: 'ki', name: 'Kikuyu, Gikuyu', key: 'Gĩkũyũ' },
  { code: 'rw', name: 'Kinyarwanda', key: 'Ikinyarwanda' },
  { code: 'ky', name: 'Kirghiz, Kyrgyz', key: 'кыргыз тили' },
  { code: 'kv', name: 'Komi', key: 'коми кыв' },
  { code: 'kg', name: 'Kongo', key: 'KiKongo' },
  { code: 'ko', name: 'Korean', key: '한국어 (韓國語), 조선말 (朝鮮語)' },
  { code: 'ku', name: 'Kurdish', key: 'Kurdî, كوردی‎' },
  { code: 'kj', name: 'Kwanyama, Kuanyama', key: 'Kuanyama' },
  { code: 'la', name: 'Latin', key: 'latine, lingua latina' },
  { code: 'lb', name: 'Luxembourgish, Letzeburgesch', key: 'Lëtzebuergesch' },
  { code: 'lg', name: 'Luganda', key: 'Luganda' },
  { code: 'li', name: 'Limburgish, Limburgan, Limburger', key: 'Limburgs' },
  { code: 'ln', name: 'Lingala', key: 'Lingála' },
  { code: 'lo', name: 'Lao', key: 'ພາສາລາວ' },
  { code: 'lt', name: 'Lithuanian', key: 'lietuvių kalba' },
  { code: 'lu', name: 'Luba-Katanga', key: '' },
  { code: 'lv', name: 'Latvian', key: 'latviešu valoda' },
  { code: 'gv', name: 'Manx', key: 'Gaelg, Gailck' },
  { code: 'mk', name: 'Macedonian', key: 'македонски јазик' },
  { code: 'mg', name: 'Malagasy', key: 'Malagasy fiteny' },
  { code: 'ms', name: 'Malay', key: 'bahasa Melayu, بهاس ملايو‎' },
  { code: 'ml', name: 'Malayalam', key: 'മലയാളം' },
  { code: 'mt', name: 'Maltese', key: 'Malti' },
  { code: 'mi', name: 'Māori', key: 'te reo Māori' },
  { code: 'mr', name: 'Marathi (Marāṭhī)', key: 'मराठी' },
  { code: 'mh', name: 'Marshallese', key: 'Kajin M̧ajeļ' },
  { code: 'mn', name: 'Mongolian', key: 'монгол' },
  { code: 'na', name: 'Nauru', key: 'Ekakairũ Naoero' },
  { code: 'nv', name: 'Navajo, Navaho', key: 'Diné bizaad, Dinékʼehǰí' },
  { code: 'nb', name: 'Norwegian Bokmål', key: 'Norsk bokmål' },
  { code: 'nd', name: 'North Ndebele', key: 'isiNdebele' },
  { code: 'ne', name: 'Nepali', key: 'नेपाली' },
  { code: 'ng', name: 'Ndonga', key: 'Owambo' },
  { code: 'nn', name: 'Norwegian Nynorsk', key: 'Norsk nynorsk' },
  { code: 'no', name: 'Norwegian', key: 'Norsk' },
  { code: 'ii', name: 'Nuosu', key: 'ꆈꌠ꒿ Nuosuhxop' },
  { code: 'nr', name: 'South Ndebele', key: 'isiNdebele' },
  { code: 'oc', name: 'Occitan', key: 'Occitan' },
  { code: 'oj', name: 'Ojibwe, Ojibwa', key: 'ᐊᓂᔑᓈᐯᒧᐎᓐ' },
  {
    code: 'cu',
    name: 'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic',
    key: 'ѩзыкъ словѣньскъ',
  },
  { code: 'om', name: 'Oromo', key: 'Afaan Oromoo' },
  { code: 'or', name: 'Oriya', key: 'ଓଡ଼ିଆ' },
  { code: 'os', name: 'Ossetian, Ossetic', key: 'ирон æвзаг' },
  { code: 'pa', name: 'Panjabi, Punjabi', key: 'ਪੰਜਾਬੀ, پنجابی‎' },
  { code: 'pi', name: 'Pāli', key: 'पाऴि' },
  { code: 'fa', name: 'Persian', key: 'فارسی' },
  { code: 'pl', name: 'Polish', key: 'polski' },
  { code: 'ps', name: 'Pashto, Pushto', key: 'پښتو' },
  { code: 'pt', name: 'Portuguese', key: 'Português' },
  { code: 'qu', name: 'Quechua', key: 'Runa Simi, Kichwa' },
  { code: 'rm', name: 'Romansh', key: 'rumantsch grischun' },
  { code: 'rn', name: 'Kirundi', key: 'kiRundi' },
  { code: 'ro', name: 'Romanian, Moldavian, Moldovan', key: 'română' },
  { code: 'ru', name: 'Russian', key: 'русский язык' },
  { code: 'sa', name: 'Sanskrit (Saṁskṛta)', key: 'संस्कृतम्' },
  { code: 'sc', name: 'Sardinian', key: 'sardu' },
  { code: 'sd', name: 'Sindhi', key: 'सिन्धी, سنڌي، سندھی‎' },
  { code: 'se', name: 'Northern Sami', key: 'Davvisámegiella' },
  { code: 'sm', name: 'Samoan', key: 'gagana faa Samoa' },
  { code: 'sg', name: 'Sango', key: 'yângâ tî sängö' },
  { code: 'sr', name: 'Serbian', key: 'српски језик' },
  { code: 'gd', name: 'Scottish Gaelic; Gaelic', key: 'Gàidhlig' },
  { code: 'sn', name: 'Shona', key: 'chiShona' },
  { code: 'si', name: 'Sinhala, Sinhalese', key: 'සිංහල' },
  { code: 'sk', name: 'Slovak', key: 'slovenčina' },
  { code: 'sl', name: 'Slovene', key: 'slovenščina' },
  { code: 'so', name: 'Somali', key: 'Soomaaliga, af Soomaali' },
  { code: 'st', name: 'Southern Sotho', key: 'Sesotho' },
  { code: 'es', name: 'Spanish; Castilian', key: 'español, castellano' },
  { code: 'su', name: 'Sundanese', key: 'Basa Sunda' },
  { code: 'sw', name: 'Swahili', key: 'Kiswahili' },
  { code: 'ss', name: 'Swati', key: 'SiSwati' },
  { code: 'sv', name: 'Swedish', key: 'svenska' },
  { code: 'ta', name: 'Tamil', key: 'தமிழ்' },
  { code: 'te', name: 'Telugu', key: 'తెలుగు' },
  { code: 'tg', name: 'Tajik', key: 'тоҷикӣ, toğikī, تاجیکی‎' },
  { code: 'th', name: 'Thai', key: 'ไทย' },
  { code: 'ti', name: 'Tigrinya', key: 'ትግርኛ' },
  { code: 'bo', name: 'Tibetan Standard, Tibetan, Central', key: 'བོད་ཡིག' },
  { code: 'tk', name: 'Turkmen', key: 'Türkmen, Түркмен' },
  { code: 'tl', name: 'Tagalog', key: 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔' },
  { code: 'tn', name: 'Tswana', key: 'Setswana' },
  { code: 'to', name: 'Tonga (Tonga Islands)', key: 'faka Tonga' },
  { code: 'tr', name: 'Turkish', key: 'Türkçe' },
  { code: 'ts', name: 'Tsonga', key: 'Xitsonga' },
  { code: 'tt', name: 'Tatar', key: 'татарча, tatarça, تاتارچا‎' },
  { code: 'tw', name: 'Twi', key: 'Twi' },
  { code: 'ty', name: 'Tahitian', key: 'Reo Tahiti' },
  { code: 'ug', name: 'Uighur, Uyghur', key: 'Uyƣurqə, ئۇيغۇرچە‎' },
  { code: 'uk', name: 'Ukrainian', key: 'українська' },
  { code: 'ur', name: 'Urdu', key: 'اردو' },
  { code: 'uz', name: 'Uzbek', key: 'zbek, Ўзбек, أۇزبېك‎' },
  { code: 've', name: 'Venda', key: 'Tshivenḓa' },
  { code: 'vi', name: 'Vietnamese', key: 'Tiếng Việt' },
  { code: 'vo', name: 'Volapük', key: 'Volapük' },
  { code: 'wa', name: 'Walloon', key: 'Walon' },
  { code: 'cy', name: 'Welsh', key: 'Cymraeg' },
  { code: 'wo', name: 'Wolof', key: 'Wollof' },
  { code: 'fy', name: 'Western Frisian', key: 'Frysk' },
  { code: 'xh', name: 'Xhosa', key: 'isiXhosa' },
  { code: 'yi', name: 'Yiddish', key: 'ייִדיש' },
  { code: 'yo', name: 'Yoruba', key: 'Yorùbá' },
  { code: 'za', name: 'Zhuang, Chuang', key: 'Saɯ cueŋƅ, Saw cuengh' },
];
